services:
  nginx:
    image: nginx:stable
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./letsencrypt:/etc/letsencrypt
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    environment:
      NEXT_PUBLIC_BACKEND_HOST_URL: ${PROD_URL}
      NEXT_PUBLIC_BACKEND_URL: ${PROD_URL}
      NEXT_PUBLIC_SOLANA_NETWORK: ${SOLANA_NETWORK}
      NEXT_PUBLIC_APP_URL: ${PROD_URL}
      NEXT_PUBLIC_TREASURY_ADDRESS: ${TREASURY_ADDRESS}
      NEXT_PUBLIC_SOFT_BURN_ADDRESS: ${SOFT_BURN_ADDRESS}
      NEXT_PUBLIC_SOLANA_RPC_MAINNET: ${SOLANA_RPC_MAINNET}
      ADMIN_API_KEY: ${ADMIN_API_KEY}
      NODE_ENV: production
    expose:
      - "3000"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    environment:
      PORT: 8000
      MONGODB_URI: ${PROD_MONGODB_URI}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      SOLANA_NETWORK: ${SOLANA_NETWORK}
      SOLANA_RPC_MAINNET: ${SOLANA_RPC_MAINNET}
      FRONTEND_URL: ${PROD_URL}
      NODE_ENV: production
      ADMIN_API_KEY: ${ADMIN_API_KEY}
      TREASURY_ADDRESS: ${TREASURY_ADDRESS}
      SOFT_BURN_ADDRESS: ${SOFT_BURN_ADDRESS}
    expose:
      - "8000"
    restart: unless-stopped
